# Generated by Django 4.1.7 on 2023-03-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('Date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('reg_link', models.CharField(max_length=50)),
                ('Poster_link', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sig',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Description', models.TextField()),
                ('Syllabus', models.CharField(max_length=50)),
                ('Sig_logo', models.ImageField(default=None, upload_to='Sig_logos')),
                ('Head', models.CharField(max_length=100, unique=True)),
                ('subhead', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_member', models.CharField(choices=[('prime-core', 'prime-core'), ('core', 'core'), ('sub-heads', 'sub-heads'), ('faculty-cordinator', 'faculty-cordinator')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('linkdin', models.CharField(max_length=50)),
                ('About', models.TextField()),
                ('Post', models.CharField(choices=[('President', 'President'), ('Secretary', 'Secretary'), ('Joint Secretary', 'Joint Secretary'), ('Technical', 'Technical'), ('Documentation', 'Documentation'), ('Social', 'Social'), ('Promotion', 'Promotion'), ('Flutter', 'Flutter'), ('Outreach', 'Outreach'), ('Python', 'Python'), ('Java', 'Java'), ('Web', 'Web'), ('C++ & DS', 'C++ & DS')], default=None, max_length=20)),
            ],
        ),
    ]
