# Generated by Django 4.1.7 on 2023-03-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='display_img',
            field=models.ImageField(default=None, upload_to='Member_images'),
        ),
    ]
