# Generated by Django 4.1.7 on 2023-03-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_display_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sig',
            name='Sig_logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='display_img',
        ),
        migrations.AddField(
            model_name='team',
            name='imgage_key',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
