# Generated by Django 4.1.7 on 2023-03-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_sig_sig_logo_remove_team_display_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Non-Tech', 'Non-Tech')], default=None, max_length=8),
        ),
    ]
